[
    {
        "author_association": "NONE",
        "body": "Ah, great description of the problem [here](http://effbot.org/pyfaq/when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2.htm).\n",
        "created_at": "2015-11-09T18:09:16Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/24#issuecomment-155143052",
        "id": 155143052,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24",
        "node_id": "MDEyOklzc3VlQ29tbWVudDE1NTE0MzA1Mg==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/155143052/reactions"
        },
        "updated_at": "2015-11-09T18:09:16Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/155143052",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/125003?v=4",
            "events_url": "https://api.github.com/users/samuell/events{/privacy}",
            "followers_url": "https://api.github.com/users/samuell/followers",
            "following_url": "https://api.github.com/users/samuell/following{/other_user}",
            "gists_url": "https://api.github.com/users/samuell/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/samuell",
            "id": 125003,
            "login": "samuell",
            "node_id": "MDQ6VXNlcjEyNTAwMw==",
            "organizations_url": "https://api.github.com/users/samuell/orgs",
            "received_events_url": "https://api.github.com/users/samuell/received_events",
            "repos_url": "https://api.github.com/users/samuell/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/samuell/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/samuell/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/samuell"
        }
    },
    {
        "author_association": "CONTRIBUTOR",
        "body": "For now, you can build your own pip package via instructions [here](http://tensorflow.org/get_started/os_setup.md); see \"Create the pip package and install\".  Let us know if that doesn't work.\n",
        "created_at": "2015-11-09T18:21:28Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/24#issuecomment-155145978",
        "id": 155145978,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24",
        "node_id": "MDEyOklzc3VlQ29tbWVudDE1NTE0NTk3OA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/155145978/reactions"
        },
        "updated_at": "2015-11-09T18:21:28Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/155145978",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/1794715?v=4",
            "events_url": "https://api.github.com/users/ebrevdo/events{/privacy}",
            "followers_url": "https://api.github.com/users/ebrevdo/followers",
            "following_url": "https://api.github.com/users/ebrevdo/following{/other_user}",
            "gists_url": "https://api.github.com/users/ebrevdo/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/ebrevdo",
            "id": 1794715,
            "login": "ebrevdo",
            "node_id": "MDQ6VXNlcjE3OTQ3MTU=",
            "organizations_url": "https://api.github.com/users/ebrevdo/orgs",
            "received_events_url": "https://api.github.com/users/ebrevdo/received_events",
            "repos_url": "https://api.github.com/users/ebrevdo/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/ebrevdo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ebrevdo/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/ebrevdo"
        }
    },
    {
        "author_association": "NONE",
        "body": "Please re-open if there's something left to diagnose here!\n",
        "created_at": "2015-11-13T22:26:57Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/24#issuecomment-156576302",
        "id": 156576302,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24",
        "node_id": "MDEyOklzc3VlQ29tbWVudDE1NjU3NjMwMg==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/156576302/reactions"
        },
        "updated_at": "2015-11-13T22:26:57Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/156576302",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/463737?v=4",
            "events_url": "https://api.github.com/users/vrv/events{/privacy}",
            "followers_url": "https://api.github.com/users/vrv/followers",
            "following_url": "https://api.github.com/users/vrv/following{/other_user}",
            "gists_url": "https://api.github.com/users/vrv/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/vrv",
            "id": 463737,
            "login": "vrv",
            "node_id": "MDQ6VXNlcjQ2MzczNw==",
            "organizations_url": "https://api.github.com/users/vrv/orgs",
            "received_events_url": "https://api.github.com/users/vrv/received_events",
            "repos_url": "https://api.github.com/users/vrv/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/vrv/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vrv/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/vrv"
        }
    },
    {
        "author_association": "NONE",
        "body": "I'm seeing what might be a related error:\n\n`_pywrap_tensorflow.so: undefined symbol: cudnnCreate`\n\nFull traceback\n\n``` bash\njvanderdoes@ubuntu:~/Code/tensorflow/tensorflow/models/image/imagenet$ python ./classify_image.py \nI tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcublas.so.7.0 locally\nI tensorflow/stream_executor/dso_loader.cc:93] Couldn't open CUDA library libcudnn.so.6.5. LD_LIBRARY_PATH: /usr/local/cuda-7.0/lib64\nI tensorflow/stream_executor/cuda/cuda_dnn.cc:1382] Unable to load cuDNN DSO\nI tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcufft.so.7.0 locally\nI tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcuda.so locally\nI tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcurand.so.7.0 locally\nI tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 2\nI tensorflow/core/common_runtime/gpu/gpu_init.cc:103] Found device 0 with properties: \nname: GeForce GTX 960\nmajor: 5 minor: 2 memoryClockRate (GHz) 1.342\npciBusID 0000:03:00.0\nTotal memory: 4.00GiB\nFree memory: 3.91GiB\nI tensorflow/core/common_runtime/gpu/gpu_init.cc:127] DMA: 0 \nI tensorflow/core/common_runtime/gpu/gpu_init.cc:137] 0:   Y \nI tensorflow/core/common_runtime/gpu/gpu_device.cc:702] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:03:00.0)\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Allocating 3.62GiB bytes.\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:52] GPU 0 memory begins at 0x402780000 extends to 0x4e9f61000\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 1.0KiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 2.0KiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 4.0KiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 8.0KiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 16.0KiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 32.0KiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 64.0KiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 128.0KiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 256.0KiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 512.0KiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 1.00MiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 2.00MiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 4.00MiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 8.00MiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 16.00MiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 32.00MiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 64.00MiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 128.00MiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 256.00MiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 512.00MiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 1.00GiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 2.00GiB\nI tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 4.00GiB\nI tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 2\nF tensorflow/stream_executor/cuda/cuda_dnn.cc:207] could not find cudnnCreate in cudnn DSO; dlerror: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cudnnCreate\n```\n",
        "created_at": "2015-12-13T00:03:18Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/24#issuecomment-164203526",
        "id": 164203526,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24",
        "node_id": "MDEyOklzc3VlQ29tbWVudDE2NDIwMzUyNg==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/164203526/reactions"
        },
        "updated_at": "2015-12-13T00:03:18Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/164203526",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/247092?v=4",
            "events_url": "https://api.github.com/users/FreakTheMighty/events{/privacy}",
            "followers_url": "https://api.github.com/users/FreakTheMighty/followers",
            "following_url": "https://api.github.com/users/FreakTheMighty/following{/other_user}",
            "gists_url": "https://api.github.com/users/FreakTheMighty/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/FreakTheMighty",
            "id": 247092,
            "login": "FreakTheMighty",
            "node_id": "MDQ6VXNlcjI0NzA5Mg==",
            "organizations_url": "https://api.github.com/users/FreakTheMighty/orgs",
            "received_events_url": "https://api.github.com/users/FreakTheMighty/received_events",
            "repos_url": "https://api.github.com/users/FreakTheMighty/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/FreakTheMighty/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/FreakTheMighty/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/FreakTheMighty"
        }
    },
    {
        "author_association": "NONE",
        "body": "My apologies, I was simply missing cudnn. :/\n",
        "created_at": "2015-12-13T00:44:17Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/24#issuecomment-164204980",
        "id": 164204980,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24",
        "node_id": "MDEyOklzc3VlQ29tbWVudDE2NDIwNDk4MA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/164204980/reactions"
        },
        "updated_at": "2015-12-13T00:44:17Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/164204980",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/247092?v=4",
            "events_url": "https://api.github.com/users/FreakTheMighty/events{/privacy}",
            "followers_url": "https://api.github.com/users/FreakTheMighty/followers",
            "following_url": "https://api.github.com/users/FreakTheMighty/following{/other_user}",
            "gists_url": "https://api.github.com/users/FreakTheMighty/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/FreakTheMighty",
            "id": 247092,
            "login": "FreakTheMighty",
            "node_id": "MDQ6VXNlcjI0NzA5Mg==",
            "organizations_url": "https://api.github.com/users/FreakTheMighty/orgs",
            "received_events_url": "https://api.github.com/users/FreakTheMighty/received_events",
            "repos_url": "https://api.github.com/users/FreakTheMighty/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/FreakTheMighty/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/FreakTheMighty/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/FreakTheMighty"
        }
    },
    {
        "author_association": "NONE",
        "body": "@FreakTheMighty\r\nI have the same problem,but I don't understand what's your mean'My apologies, I was simply missing cudnn. :/' ,could express more clearly?",
        "created_at": "2016-11-23T09:00:41Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/24#issuecomment-262461714",
        "id": 262461714,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24",
        "node_id": "MDEyOklzc3VlQ29tbWVudDI2MjQ2MTcxNA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/262461714/reactions"
        },
        "updated_at": "2016-11-23T09:00:41Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/262461714",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/21114260?v=4",
            "events_url": "https://api.github.com/users/andongchen/events{/privacy}",
            "followers_url": "https://api.github.com/users/andongchen/followers",
            "following_url": "https://api.github.com/users/andongchen/following{/other_user}",
            "gists_url": "https://api.github.com/users/andongchen/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/andongchen",
            "id": 21114260,
            "login": "andongchen",
            "node_id": "MDQ6VXNlcjIxMTE0MjYw",
            "organizations_url": "https://api.github.com/users/andongchen/orgs",
            "received_events_url": "https://api.github.com/users/andongchen/received_events",
            "repos_url": "https://api.github.com/users/andongchen/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/andongchen/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/andongchen/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/andongchen"
        }
    }
]