[
    {
        "author_association": "CONTRIBUTOR",
        "body": "Was able to execute the given code without any error on colab with Tensorflow 1.12.0. Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/b865119741330d3fd1a5ebcbb4f4d157/untitled128.ipynb). Thanks!",
        "created_at": "2019-09-09T06:10:48Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/32314#issuecomment-529314248",
        "id": 529314248,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/32314",
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyOTMxNDI0OA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/529314248/reactions"
        },
        "updated_at": "2019-09-09T06:10:48Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/529314248",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/48476109?v=4",
            "events_url": "https://api.github.com/users/gadagashwini-zz/events{/privacy}",
            "followers_url": "https://api.github.com/users/gadagashwini-zz/followers",
            "following_url": "https://api.github.com/users/gadagashwini-zz/following{/other_user}",
            "gists_url": "https://api.github.com/users/gadagashwini-zz/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/gadagashwini-zz",
            "id": 48476109,
            "login": "gadagashwini-zz",
            "node_id": "MDQ6VXNlcjQ4NDc2MTA5",
            "organizations_url": "https://api.github.com/users/gadagashwini-zz/orgs",
            "received_events_url": "https://api.github.com/users/gadagashwini-zz/received_events",
            "repos_url": "https://api.github.com/users/gadagashwini-zz/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/gadagashwini-zz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/gadagashwini-zz/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/gadagashwini-zz"
        }
    },
    {
        "author_association": "NONE",
        "body": "it's very weird because I can run the code in colab but not on my own computer, so do I just turn to colab from now on?",
        "created_at": "2019-09-09T10:47:32Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/32314#issuecomment-529412686",
        "id": 529412686,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/32314",
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyOTQxMjY4Ng==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/529412686/reactions"
        },
        "updated_at": "2019-09-09T10:47:32Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/529412686",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/44339880?v=4",
            "events_url": "https://api.github.com/users/Arcannite/events{/privacy}",
            "followers_url": "https://api.github.com/users/Arcannite/followers",
            "following_url": "https://api.github.com/users/Arcannite/following{/other_user}",
            "gists_url": "https://api.github.com/users/Arcannite/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Arcannite",
            "id": 44339880,
            "login": "Arcannite",
            "node_id": "MDQ6VXNlcjQ0MzM5ODgw",
            "organizations_url": "https://api.github.com/users/Arcannite/orgs",
            "received_events_url": "https://api.github.com/users/Arcannite/received_events",
            "repos_url": "https://api.github.com/users/Arcannite/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Arcannite/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Arcannite/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Arcannite"
        }
    },
    {
        "author_association": "CONTRIBUTOR",
        "body": "This looks like a proxy configuration issue where you are trying to connect from firewall corporate network. \r\nThe workaround can be;\r\nYou can download the data from this link\r\nhttps://www.kaggle.com/zalando-research/fashionmnist\r\nLater you can use ```tf.keras.utils.get_file``` to load the dataset.\r\nSee,\r\nhttps://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file",
        "created_at": "2019-09-09T18:01:06Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/32314#issuecomment-529596769",
        "id": 529596769,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/32314",
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyOTU5Njc2OQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/529596769/reactions"
        },
        "updated_at": "2019-09-09T18:01:06Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/529596769",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/42785357?v=4",
            "events_url": "https://api.github.com/users/ymodak/events{/privacy}",
            "followers_url": "https://api.github.com/users/ymodak/followers",
            "following_url": "https://api.github.com/users/ymodak/following{/other_user}",
            "gists_url": "https://api.github.com/users/ymodak/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/ymodak",
            "id": 42785357,
            "login": "ymodak",
            "node_id": "MDQ6VXNlcjQyNzg1MzU3",
            "organizations_url": "https://api.github.com/users/ymodak/orgs",
            "received_events_url": "https://api.github.com/users/ymodak/received_events",
            "repos_url": "https://api.github.com/users/ymodak/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/ymodak/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ymodak/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/ymodak"
        }
    },
    {
        "author_association": "NONE",
        "body": "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=32314\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=32314\">No</a>\n",
        "created_at": "2019-09-12T17:28:30Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/32314#issuecomment-530925739",
        "id": 530925739,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/32314",
        "node_id": "MDEyOklzc3VlQ29tbWVudDUzMDkyNTczOQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/530925739/reactions"
        },
        "updated_at": "2019-09-12T17:28:30Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/530925739",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/1913207?v=4",
            "events_url": "https://api.github.com/users/tensorflow-bot%5Bbot%5D/events{/privacy}",
            "followers_url": "https://api.github.com/users/tensorflow-bot%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/tensorflow-bot%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/tensorflow-bot%5Bbot%5D/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/apps/tensorflow-bot",
            "id": 48739277,
            "login": "tensorflow-bot[bot]",
            "node_id": "MDM6Qm90NDg3MzkyNzc=",
            "organizations_url": "https://api.github.com/users/tensorflow-bot%5Bbot%5D/orgs",
            "received_events_url": "https://api.github.com/users/tensorflow-bot%5Bbot%5D/received_events",
            "repos_url": "https://api.github.com/users/tensorflow-bot%5Bbot%5D/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/tensorflow-bot%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tensorflow-bot%5Bbot%5D/subscriptions",
            "type": "Bot",
            "url": "https://api.github.com/users/tensorflow-bot%5Bbot%5D"
        }
    },
    {
        "author_association": "NONE",
        "body": "is this issue has solved?",
        "created_at": "2020-09-14T16:41:59Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/32314#issuecomment-692176090",
        "id": 692176090,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/32314",
        "node_id": "MDEyOklzc3VlQ29tbWVudDY5MjE3NjA5MA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/692176090/reactions"
        },
        "updated_at": "2020-09-14T16:41:59Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/692176090",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/49846800?v=4",
            "events_url": "https://api.github.com/users/matdadi/events{/privacy}",
            "followers_url": "https://api.github.com/users/matdadi/followers",
            "following_url": "https://api.github.com/users/matdadi/following{/other_user}",
            "gists_url": "https://api.github.com/users/matdadi/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/matdadi",
            "id": 49846800,
            "login": "matdadi",
            "node_id": "MDQ6VXNlcjQ5ODQ2ODAw",
            "organizations_url": "https://api.github.com/users/matdadi/orgs",
            "received_events_url": "https://api.github.com/users/matdadi/received_events",
            "repos_url": "https://api.github.com/users/matdadi/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/matdadi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/matdadi/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/matdadi"
        }
    },
    {
        "author_association": "NONE",
        "body": "no, when I run the code above with the newest version of tensorflow, it gives a different error:\r\n`OSError: Not a gzipped file (b'\\x00\\x00')`\r\n",
        "created_at": "2020-09-15T08:29:41Z",
        "html_url": "https://github.com/tensorflow/tensorflow/issues/32314#issuecomment-692556665",
        "id": 692556665,
        "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/32314",
        "node_id": "MDEyOklzc3VlQ29tbWVudDY5MjU1NjY2NQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/692556665/reactions"
        },
        "updated_at": "2020-09-15T08:29:41Z",
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/692556665",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/44339880?v=4",
            "events_url": "https://api.github.com/users/Arcannite/events{/privacy}",
            "followers_url": "https://api.github.com/users/Arcannite/followers",
            "following_url": "https://api.github.com/users/Arcannite/following{/other_user}",
            "gists_url": "https://api.github.com/users/Arcannite/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Arcannite",
            "id": 44339880,
            "login": "Arcannite",
            "node_id": "MDQ6VXNlcjQ0MzM5ODgw",
            "organizations_url": "https://api.github.com/users/Arcannite/orgs",
            "received_events_url": "https://api.github.com/users/Arcannite/received_events",
            "repos_url": "https://api.github.com/users/Arcannite/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Arcannite/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Arcannite/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Arcannite"
        }
    }
]