[
    {
        "author_association": "NONE",
        "body": "I have the same problem. In my case, this error was caused by this package: `pywatchman`.",
        "created_at": "2021-02-08T11:57:25Z",
        "html_url": "https://github.com/ipython/ipython/issues/12741#issuecomment-775093557",
        "id": 775093557,
        "issue_url": "https://api.github.com/repos/ipython/ipython/issues/12741",
        "node_id": "MDEyOklzc3VlQ29tbWVudDc3NTA5MzU1Nw==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/ipython/ipython/issues/comments/775093557/reactions"
        },
        "updated_at": "2021-02-08T11:57:25Z",
        "url": "https://api.github.com/repos/ipython/ipython/issues/comments/775093557",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/320373?v=4",
            "events_url": "https://api.github.com/users/illagrenan/events{/privacy}",
            "followers_url": "https://api.github.com/users/illagrenan/followers",
            "following_url": "https://api.github.com/users/illagrenan/following{/other_user}",
            "gists_url": "https://api.github.com/users/illagrenan/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/illagrenan",
            "id": 320373,
            "login": "illagrenan",
            "node_id": "MDQ6VXNlcjMyMDM3Mw==",
            "organizations_url": "https://api.github.com/users/illagrenan/orgs",
            "received_events_url": "https://api.github.com/users/illagrenan/received_events",
            "repos_url": "https://api.github.com/users/illagrenan/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/illagrenan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/illagrenan/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/illagrenan"
        }
    },
    {
        "author_association": "MEMBER",
        "body": "@sandguardian could you please give the full log? It's difficult to go by just last line of a traceback. Why do you think its an issue with IPython?",
        "created_at": "2021-04-20T20:39:24Z",
        "html_url": "https://github.com/ipython/ipython/issues/12741#issuecomment-823585616",
        "id": 823585616,
        "issue_url": "https://api.github.com/repos/ipython/ipython/issues/12741",
        "node_id": "MDEyOklzc3VlQ29tbWVudDgyMzU4NTYxNg==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/ipython/ipython/issues/comments/823585616/reactions"
        },
        "updated_at": "2021-04-21T00:50:02Z",
        "url": "https://api.github.com/repos/ipython/ipython/issues/comments/823585616",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/6691643?v=4",
            "events_url": "https://api.github.com/users/MrMino/events{/privacy}",
            "followers_url": "https://api.github.com/users/MrMino/followers",
            "following_url": "https://api.github.com/users/MrMino/following{/other_user}",
            "gists_url": "https://api.github.com/users/MrMino/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/MrMino",
            "id": 6691643,
            "login": "MrMino",
            "node_id": "MDQ6VXNlcjY2OTE2NDM=",
            "organizations_url": "https://api.github.com/users/MrMino/orgs",
            "received_events_url": "https://api.github.com/users/MrMino/received_events",
            "repos_url": "https://api.github.com/users/MrMino/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/MrMino/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MrMino/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/MrMino"
        }
    },
    {
        "author_association": "MEMBER",
        "body": "I'm going to close this in the interest of having a cleaner issue backlog. Should you encounter this again, please ping us here, and add the full traceback.",
        "created_at": "2022-03-27T18:12:56Z",
        "html_url": "https://github.com/ipython/ipython/issues/12741#issuecomment-1079987296",
        "id": 1079987296,
        "issue_url": "https://api.github.com/repos/ipython/ipython/issues/12741",
        "node_id": "IC_kwDOAAoMVs5AX0xg",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/ipython/ipython/issues/comments/1079987296/reactions"
        },
        "updated_at": "2022-03-27T18:12:56Z",
        "url": "https://api.github.com/repos/ipython/ipython/issues/comments/1079987296",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/6691643?v=4",
            "events_url": "https://api.github.com/users/MrMino/events{/privacy}",
            "followers_url": "https://api.github.com/users/MrMino/followers",
            "following_url": "https://api.github.com/users/MrMino/following{/other_user}",
            "gists_url": "https://api.github.com/users/MrMino/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/MrMino",
            "id": 6691643,
            "login": "MrMino",
            "node_id": "MDQ6VXNlcjY2OTE2NDM=",
            "organizations_url": "https://api.github.com/users/MrMino/orgs",
            "received_events_url": "https://api.github.com/users/MrMino/received_events",
            "repos_url": "https://api.github.com/users/MrMino/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/MrMino/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MrMino/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/MrMino"
        }
    }
]