{"id": "ROOT", "speaker": "DaniilAnichin", "conversation_id": "ROOT", "reply_to": "ROOT", "timestamp": "2020-12-25T12:54:33Z", "text": "Last jedi release (0.18.0) is incompatible with ipython (7.19 and 7.18 tested); reason - column arg was deprecated, and now removed <!-- This is the repository for IPython command line, if you can try to make sure this question/bug/feature belong here and not on one of the Jupyter repositories. \r \r If it's a generic Python/Jupyter question, try other forums or discourse.jupyter.org.\r \r If you are unsure, it's ok to post here, though, there are few maintainer so you might not get a fast response. \r \r Ability of maintainers to spend time and resources on project like IPython is heavily influenced by US politics, and the current government policies have been harmful to the IPython Maintainers and Community. \r \r If you are on the fence on who to vote for or wether to vote, please cast your vote in for the democrat party in the US.\r -->\r Relevant traceback reads as follows: \r ```\r   File \"../venv/lib/python3.8/site-packages/IPython/core/completer.py\", line 2029, in _complete\r     completions = self._jedi_matches(\r   File \"../venv/lib/python3.8/site-packages/IPython/core/completer.py\", line 1373, in _jedi_matches\r     interpreter = jedi.Interpreter(\r   File \"../venv/lib/python3.8/site-packages/jedi/api/__init__.py\", line 725, in __init__\r     super().__init__(code, environment=environment,\r TypeError: __init__() got an unexpected keyword argument 'column'\r ```\r \r sys info: \r ```\r {'commit_hash': '62779a198',\r  'commit_source': 'installation',\r  'default_encoding': 'utf-8',\r  'ipython_path': '../venv/lib/python3.8/site-packages/IPython',\r  'ipython_version': '7.18.0',\r  'os_name': 'posix',\r  'platform': 'Linux-4.15.0-128-generic-x86_64-with-glibc2.17',\r  'sys_executable': '../venv/bin/python',\r  'sys_platform': 'linux',\r  'sys_version': '3.8.5 (default, Jul 20 2020, 19:50:14) \\n[GCC 5.4.0 20160609]'}\r ```\r same reported in jedi repo too", "meta": {"posReactions": "251", "negReactions": "0"}}
{"id": "COM0", "speaker": "benwu95", "conversation_id": "ROOT", "reply_to": "ROOT", "timestamp": "2020-12-25T17:15:20Z", "text": "https://github.com/ipython/ipython/commit/dcd9dc90aee7e4c5c52ce44c18e7518934790612\r\n\r\nThe code has been already updated, but `7.19.0` did not include this. :(", "meta": {"posReactions": "17", "negReactions": "0"}}
{"id": "COM1", "speaker": "davidhalter", "conversation_id": "ROOT", "reply_to": "COM0", "timestamp": "2020-12-25T17:20:36Z", "text": "As a temporary fix for anyone just trying to get things working again:\r\n\r\n```\r\npip install jedi==0.17.2\r\n```\r\n\r\n----\r\n\r\nIt would be really nice if you could quickly release a 7.19.1. (It's already fixed on master).\r\n\r\nSorry for that. I did not realize that IPython with that fix was not released yet. I usually test IPython completions before doing a Jedi release, but not this time :/. It will probably also not happen in the future anymore, because I'm going to release Jedi 1.0 soon, so this is probably the last time for a long time that you have to deal with deprecations in Jedi.\r\n\r\nStill wish you a Merry Christmas!", "meta": {"posReactions": "239", "negReactions": "0"}}
{"id": "COM2", "speaker": "davidhalter", "conversation_id": "ROOT", "reply_to": "COM1", "timestamp": "2020-12-25T17:26:00Z", "text": "By the way, a `7.19.1` release with the dependency `jedi<0.18.0` would also suffice.", "meta": {"posReactions": "13", "negReactions": "0"}}
{"id": "COM3", "speaker": "jkryanchou", "conversation_id": "ROOT", "reply_to": "COM2", "timestamp": "2020-12-27T04:33:25Z", "text": "@davidhalter Thanks for your solution. it finally work.", "meta": {"posReactions": "1", "negReactions": "0"}}
{"id": "COM4", "speaker": "SamuelDSR", "conversation_id": "ROOT", "reply_to": "COM3", "timestamp": "2020-12-27T14:53:49Z", "text": "I had the same problem with ipython and thanks to the solution of @davidhalter , it works again. :+1: ", "meta": {"posReactions": "1", "negReactions": "0"}}
{"id": "COM5", "speaker": "digglife", "conversation_id": "ROOT", "reply_to": "COM4", "timestamp": "2020-12-28T07:28:08Z", "text": "Thank you for opening this issue.  Happy holiday!", "meta": {"posReactions": "0", "negReactions": "0"}}
{"id": "COM6", "speaker": "yurzo", "conversation_id": "ROOT", "reply_to": "COM5", "timestamp": "2020-12-28T23:57:08Z", "text": "Posted a pr to pin the dependency as suggested: #12746", "meta": {"posReactions": "3", "negReactions": "0"}}
{"id": "COM7", "speaker": "bremme", "conversation_id": "ROOT", "reply_to": "COM6", "timestamp": "2020-12-29T02:25:19Z", "text": "Thanks a lot. I thought my shell was broken. Every time when I tried to use tab completion in IPython it crashed. Glad I found a solution.", "meta": {"posReactions": "2", "negReactions": "0"}}
{"id": "COM8", "speaker": "aprilahijriyan", "conversation_id": "ROOT", "reply_to": "COM7", "timestamp": "2020-12-29T05:05:58Z", "text": "Finally found a solution! thank you @davidhalter \ud83c\udf89 ", "meta": {"posReactions": "1", "negReactions": "0"}}
{"id": "COM9", "speaker": "tik9", "conversation_id": "ROOT", "reply_to": "COM8", "timestamp": "2020-12-31T19:47:45Z", "text": "When would the problem be fixed so that every Jedi version is compatible with ipython?", "meta": {"posReactions": "0", "negReactions": "0"}}
{"id": "COM10", "speaker": "NeilGirdhar", "conversation_id": "ROOT", "reply_to": "COM9", "timestamp": "2020-12-31T23:52:55Z", "text": "@tik9 Does installing from master work for you?\r\n\r\n    pip install git+https://github.com/ipython/ipython\r\n\r\nIf so, whenever ipython releases a new version, it will be fixed for everyone.", "meta": {"posReactions": "5", "negReactions": "0"}}
{"id": "COM11", "speaker": "tik9", "conversation_id": "ROOT", "reply_to": "COM10", "timestamp": "2021-01-01T11:07:25Z", "text": "@NeilGirdhar , when doing\r\n`pip install git+https://github.com/ipython/ipython`\r\n\r\nIt seems to work, I still have to update to the current Jedi.", "meta": {"posReactions": "3", "negReactions": "0"}}
{"id": "COM12", "speaker": "omarish", "conversation_id": "ROOT", "reply_to": "COM11", "timestamp": "2021-01-03T02:12:41Z", "text": "Got this issue as well. Pinning `jedi==0.17.2` worked for me, thanks @davidhalter.", "meta": {"posReactions": "0", "negReactions": "0"}}
{"id": "COM13", "speaker": "stefanschlipfi", "conversation_id": "ROOT", "reply_to": "COM12", "timestamp": "2021-01-03T13:05:27Z", "text": "> As a temporary fix for anyone just trying to get things working again:\r\n> \r\n> ```\r\n> pip install jedi==0.17.2\r\n> ```\r\n> \r\n> It would be really nice if you could quickly release a 7.19.1. (It's already fixed on master).\r\n> \r\n> Sorry for that. I did not realize that IPython with that fix was not released yet. I usually test IPython completions before doing a Jedi release, but not this time :/. It will probably also not happen in the future anymore, because I'm going to release Jedi 1.0 soon, so this is probably the last time for a long time that you have to deal with deprecations in Jedi.\r\n> \r\n> Still wish you a Merry Christmas!\r\n\r\nThank you for your solution.\r\nI got the same issue and IPython worked after I installed Jedi", "meta": {"posReactions": "0", "negReactions": "0"}}
{"id": "COM14", "speaker": "nicksama88", "conversation_id": "ROOT", "reply_to": "COM13", "timestamp": "2021-01-04T02:03:25Z", "text": "installing 0.17.2 of jedi also worked for me.  Was chasing my tail trying to figure out why it wasn't working in a new virtual environment, glad to have found this!  Hope the fix is out soon.  Luckily this showed up as the top link in Google for me when searching \"ipython init got an unexpected keyword argument 'column'\".", "meta": {"posReactions": "2", "negReactions": "0"}}
{"id": "COM15", "speaker": "bl-ue", "conversation_id": "ROOT", "reply_to": "COM14", "timestamp": "2021-01-04T15:30:44Z", "text": "This works:\r\n```console\r\n$ pip install 'jedi<0.18'\r\n```", "meta": {"posReactions": "0", "negReactions": "0"}}
{"id": "COM16", "speaker": "ABODFTW", "conversation_id": "ROOT", "reply_to": "COM15", "timestamp": "2021-01-04T15:54:29Z", "text": "Thanks @bl-ue\r\n\r\nFor reference, the autocomplete on my Jupyter notebook wasn't working and I was getting this same error on the terminal.\r\n\r\nAnd now it's working as expected after downgrading jedi to 0.17.2 by just executing the command @bl-ue mentioned.", "meta": {"posReactions": "1", "negReactions": "0"}}
{"id": "COM17", "speaker": "BallsyWalnuts", "conversation_id": "ROOT", "reply_to": "COM16", "timestamp": "2021-01-05T13:10:27Z", "text": "Confirmed that downgrading jedi to `0.17.2` fixed the issue for me as well. Thanks @davidhalter ", "meta": {"posReactions": "3", "negReactions": "0"}}
{"id": "COM18", "speaker": "gabrielebndn", "conversation_id": "ROOT", "reply_to": "COM17", "timestamp": "2021-01-05T18:57:28Z", "text": "Hi everyone, I've stumbled on this issue while creating docker images for myself.\r\nIf I understand correctly from [this comment](https://github.com/ipython/ipython/issues/12740#issuecomment-751273086) the problem has already been solved on master, but so far no release including the fix has been issued.\r\nIn order to better organize my own work, may I know when do you plan a new release? Somebody [here](https://github.com/ipython/ipython/issues/12740#issuecomment-751273584) was suggesting to quickly release 7.19.1, including this patch, is it still an option?", "meta": {"posReactions": "1", "negReactions": "0"}}
{"id": "COM19", "speaker": "HosseinDahaei", "conversation_id": "ROOT", "reply_to": "COM18", "timestamp": "2021-01-07T19:06:42Z", "text": "> As a temporary fix for anyone just trying to get things working again:\r\n> \r\n> ```\r\n> pip install jedi==0.17.2\r\n> ```\r\n> \r\n> It would be really nice if you could quickly release a 7.19.1. (It's already fixed on master).\r\n> \r\n> Sorry for that. I did not realize that IPython with that fix was not released yet. I usually test IPython completions before doing a Jedi release, but not this time :/. It will probably also not happen in the future anymore, because I'm going to release Jedi 1.0 soon, so this is probably the last time for a long time that you have to deal with deprecations in Jedi.\r\n> \r\n> Still wish you a Merry Christmas!\r\n\r\nthanks a lot", "meta": {"posReactions": "4", "negReactions": "0"}}
{"id": "COM20", "speaker": "LuanComputacao", "conversation_id": "ROOT", "reply_to": "COM19", "timestamp": "2021-01-09T16:45:50Z", "text": "pip install -U jedi==0.17.2 parso==0.7.1", "meta": {"posReactions": "0", "negReactions": "0"}}
{"id": "COM21", "speaker": "mostealth", "conversation_id": "ROOT", "reply_to": "COM20", "timestamp": "2021-01-11T09:12:16Z", "text": "I wonder, when you have a dependency (jedi) that is in version 0.x.y (not reached major 1), if it is not wiser to pin the minor as >=0.17,<0.18.", "meta": {"posReactions": "2", "negReactions": "0"}}
{"id": "COM22", "speaker": "yurzo", "conversation_id": "ROOT", "reply_to": "COM21", "timestamp": "2021-01-11T17:39:25Z", "text": "FYI https://github.com/ipython/ipython/pull/12751#issuecomment-758065462", "meta": {"posReactions": "1", "negReactions": "0"}}
{"id": "COM23", "speaker": "violet4", "conversation_id": "ROOT", "reply_to": "COM22", "timestamp": "2021-01-13T23:40:31Z", "text": "> As a temporary fix for anyone just trying to get things working again:\r\n> \r\n> ```\r\n> pip install jedi==0.17.2\r\n> ```\r\n> \r\n> It would be really nice if you could quickly release a 7.19.1. (It's already fixed on master).\r\n> \r\n> Sorry for that. I did not realize that IPython with that fix was not released yet. I usually test IPython completions before doing a Jedi release, but not this time :/. It will probably also not happen in the future anymore, because I'm going to release Jedi 1.0 soon, so this is probably the last time for a long time that you have to deal with deprecations in Jedi.\r\n> \r\n> Still wish you a Merry Christmas!\r\n\r\nnote: in anaconda, this has to be done in the same kernel you're using from within the jupyter notebook, not the one you're using the `jupyter notebook` command from!\r\n\r\ntook me about 30 minutes to finally figure that one out once i found @davidhalter's pip install tip (i used `conda install jedi==0.17.2` instead of pip).\r\n\r\nthank you all!", "meta": {"posReactions": "7", "negReactions": "0"}}
{"id": "COM24", "speaker": "gapster", "conversation_id": "ROOT", "reply_to": "COM23", "timestamp": "2021-01-15T17:24:05Z", "text": "Can you explain what you mean by \"same kernel ...\" vs \"using the jupyter notebook ...\"   i.e.,  will conda install jedi==0.17.2 from the shell command line do the trick?  (it seems to)", "meta": {"posReactions": "0", "negReactions": "0"}}
{"id": "COM25", "speaker": "marvinbernhardt", "conversation_id": "ROOT", "reply_to": "COM24", "timestamp": "2021-01-16T22:26:28Z", "text": "> Can you explain what you mean by \"same kernel ...\" vs \"using the jupyter notebook ...\" i.e., will conda install jedi==0.17.2 from the shell command line do the trick? (it seems to)\r\n\r\nYou can run Jupyter in one env and use it with a kernel from another env. See for example [this SO question](https://stackoverflow.com/questions/53004311/how-to-add-conda-environment-to-jupyter-lab). Jedi version of the latter env matters. If you are not aware of this, you probably use one conda env for jupyter and kernel.", "meta": {"posReactions": "1", "negReactions": "0"}}
{"id": "COM26", "speaker": "dowenk", "conversation_id": "ROOT", "reply_to": "COM25", "timestamp": "2021-01-19T18:00:21Z", "text": "The following works in ipython/jupyter.   I assume it gets jedi out of the way of the built-in completer.   Good enough for me until fix is released.\r\n\r\n%config Completer.use_jedi = False\r\n", "meta": {"posReactions": "7", "negReactions": "2"}}
{"id": "COM27", "speaker": "bl-ue", "conversation_id": "ROOT", "reply_to": "COM26", "timestamp": "2021-01-20T14:05:31Z", "text": "It does work! \ud83d\udc4d\ud83c\udffb \r\nNice find @dowenk! \ud83d\ude0d ", "meta": {"posReactions": "0", "negReactions": "0"}}
{"id": "COM28", "speaker": "davidhalter", "conversation_id": "ROOT", "reply_to": "COM27", "timestamp": "2021-01-20T17:37:46Z", "text": "Because people at this point probably don't scroll up to my comment (https://github.com/ipython/ipython/issues/12740#issuecomment-751273584), this is what you should do temporarily:\r\n\r\n```\r\npip install jedi==0.17.2\r\n```", "meta": {"posReactions": "16", "negReactions": "0"}}
{"id": "COM29", "speaker": "bl-ue", "conversation_id": "ROOT", "reply_to": "COM28", "timestamp": "2021-01-23T21:39:34Z", "text": "When is the team going to fix this? In just a month hundreds of users have encountered this issue.", "meta": {"posReactions": "2", "negReactions": "0"}}
